menu: # To remove a menu, just leave the value blank.
  projects: Projects
  services: Services
  prices: Prices
  blog: Blog
  about: Us
  contact: Contact
  
#show the subscribe area
#default false
subscribe: true

# Available themes:
#        combustion-purple
#        combustion-yellow
#        fuzzy-hue
#        fuzzy-saturation
#        ring-blue
#        ring-green
#        tunnel
#        waves-deep-purple
#        waves-light-blue
theme: ring-blue

#default featured image for posts
featured: "/img/default-new-blog.jpg"

#default background image for posts
background: "/img/default-background.jpg"
